### model
model_name_or_path: your_own_model_path

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: resistance_detection_with_explanation # resistance_detection
# packing: true
template: llama3
cutoff_len: 8192
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: your_own_model_save_path
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-7
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
optim: adamw_torch

### eval
val_size: 0


# command:
# CUDA_VISIBLE_DEVICES=xxx nohup llamafactory-cli train examples/train_lora/llama3_full_sft_resistance.yaml >output.log 2>&1 &

