### model
model_name_or_path: your_own_model_checkpoint

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: examples/deepspeed/ds_z3_config.json # for full

### dataset
dataset: resistance_detection_dpo
packing: true
template: llama3
cutoff_len: 8192
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: your_own_model_save_path
logging_steps: 10
save_steps: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-7
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
optim: adamw_torch

### eval
val_size: 0

## command:
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup llamafactory-cli train examples/train_lora/llama3_full_dpo_resistance.yaml >dpo.log 2>&1 &
